const express = require('express');
const authRoutes = require('./auth');
const usersRoutes = require('./users');
const userMobileRoutes = require('./user-mobile');
const bookingsRoutes = require('./bookings');
const teachersRoutes = require('./teachers');
const adminRoutes = require('./admin');
const paymentsRoutes = require('./payments');
const filesRoutes = require('./files');
const notificationsRoutes = require('./notifications');
const reviewsRoutes = require('./reviews');
const sessionsRoutes = require('./sessions');
const coursesRoutes = require('./courses');
const lessonsRoutes = require('./lessons');
const examsRoutes = require('./exams');
const subscriptionsRoutes = require('./subscriptions');
const studentSubscriptionsRoutes = require('./student-subscriptions');
const contentRoutes = require('./content');
const certificatesRoutes = require('./certificates');
const financeRoutes = require('./finance');
const rbacRoutes = require('./rbac');
const auditRoutes = require('./audit');
const videoRoutes = require('./video');
const v1Routes = require('./v1');
const mobileRoutes = require('./mobile');

const router = express.Router();

router.use('/auth', authRoutes);
router.use('/users', usersRoutes);
router.use('/user', userMobileRoutes);
router.use('/bookings', bookingsRoutes);
router.use('/teachers', teachersRoutes);
router.use('/admin', adminRoutes);
router.use('/payments', paymentsRoutes);
router.use('/files', filesRoutes);
router.use('/notifications', notificationsRoutes);
router.use('/reviews', reviewsRoutes);
router.use('/sessions', sessionsRoutes);
router.use('/courses', coursesRoutes);
router.use('/lessons', lessonsRoutes);
router.use('/exams', examsRoutes);
router.use('/subscriptions', subscriptionsRoutes);
router.use('/student-subscriptions', studentSubscriptionsRoutes);
router.use('/content', contentRoutes);
router.use('/certificates', certificatesRoutes);
router.use('/finance', financeRoutes);
router.use('/rbac', rbacRoutes);
router.use('/audit', auditRoutes);
router.use('/video', videoRoutes);
router.use('/v1', v1Routes);
router.use('/mobile', mobileRoutes);

module.exports = router;
