-- Add missing columns to users table
ALTER TABLE `users` 
ADD COLUMN IF NOT EXISTS `age` INT NULL,
ADD COLUMN IF NOT EXISTS `gender` ENUM('MALE', 'FEMALE') NULL,
ADD COLUMN IF NOT EXISTS `memorized_parts` INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS `student_phone` VARCHAR(191) NULL,
ADD COLUMN IF NOT EXISTS `parent_phone` VARCHAR(191) NULL;

-- Add missing columns to courses table
ALTER TABLE `courses`
ADD COLUMN IF NOT EXISTS `category` VARCHAR(191) NULL,
ADD COLUMN IF NOT EXISTS `fullDescription` LONGTEXT NULL,
ADD COLUMN IF NOT EXISTS `fullDescriptionAr` LONGTEXT NULL,
ADD COLUMN IF NOT EXISTS `introVideoThumbnail` VARCHAR(191) NULL,
ADD COLUMN IF NOT EXISTS `introVideoUrl` VARCHAR(191) NULL,
ADD COLUMN IF NOT EXISTS `isFeatured` BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS `level` ENUM('BEGINNER', 'INTERMEDIATE', 'ADVANCED') NULL,
ADD COLUMN IF NOT EXISTS `rating` DOUBLE DEFAULT 0,
ADD COLUMN IF NOT EXISTS `totalLessons` INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS `totalReviews` INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS `totalVideos` INT DEFAULT 0;

